[
    {
        "key": "datr",
        "value": "TOoQafn7LmluGzD3hLfgUHLB",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    },
    {
        "key": "sb",
        "value": "TeoQaZXgsDfVjJfs92OV46cg",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    },
    {
        "key": "ps_l",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    },
    {
        "key": "ps_n",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    },
    {
        "key": "locale",
        "value": "en_US",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B720x360x3",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    },
    {
        "key": "c_user",
        "value": "61583750574399",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    },
    {
        "key": "xs",
        "value": "2%3AYaUMHa3rpHjDBw%3A2%3A1762720585%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    },
    {
        "key": "fr",
        "value": "05cdXRgpyT61XUiD4.AWeILG_Ea7K3ezQucvjc_Uks_9gWKuGSI7jGdPyq1O-KwreuEuk.BpEOpN..AAA.0.0.BpEPtO.AWdNbZ9v-1NrQ4F1-LGewHtmRXM",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    },
    {
        "key": "pas",
        "value": "100077723076276%3A8DEKeSdXYs%2C61583750574399%3A8TkxZd9yxa",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    },
    {
        "key": "fbl_st",
        "value": "101739347%3BT%3A29378738",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2979%3Btimestamp%3A1762724292",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-09T21:40:36.389Z",
        "lastAccessed": "2025-11-09T21:40:36.389Z"
    }
]
