[
    {
        "name": "datr",
        "value": "SwMRaQjPNiDi2H1rCkQnV2By",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1797282635.307,
        "storeId": null
    },
    {
        "name": "fr",
        "value": "0xIGk2BUcUtT3U118.AWcB-J67iEBOYXRlj66TqnTWHcUILleHw3mnFiCzCzmPwpEIW78.BpEQNL..AAA.0.0.BpEQPP.AWfk9UvkUyGi5fctcnpG06wFuqQ",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1770498767.497,
        "storeId": null
    },
    {
        "name": "vpd",
        "value": "v1%3B712x360x3",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1767906768,
        "storeId": null
    },
    {
        "name": "xs",
        "value": "4%3A_11cB33eHqBLmQ%3A2%3A1762722759%3A-1%3A-1",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1794258761.318,
        "storeId": null
    },
    {
        "name": "fbl_st",
        "value": "101733943%3BT%3A29378730",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "strict",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1794259833,
        "storeId": null
    },
    {
        "name": "locale",
        "value": "en_US",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1763327567.497,
        "storeId": null
    },
    {
        "name": "m_pixel_ratio",
        "value": "1",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": null,
        "session": true,
        "firstPartyDomain": "",
        "partitionKey": null,
        "storeId": null
    },
    {
        "name": "c_user",
        "value": "61583750574399",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1794258761.318,
        "storeId": null
    },
    {
        "name": "pas",
        "value": "61583750574399%3ACItPXmhowU",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1797282767.497,
        "storeId": null
    },
    {
        "name": "sb",
        "value": "SwMRaQFnmokMDCWzCHydB0eg",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1797282761.318,
        "storeId": null
    },
    {
        "name": "wd",
        "value": "360x812",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": null,
        "session": true,
        "firstPartyDomain": "",
        "partitionKey": null,
        "storeId": null
    },
    {
        "name": "wl_cbv",
        "value": "v2%3Bclient_version%3A2979%3Btimestamp%3A1762722767",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1770498768,
        "storeId": null
    }
]
